#!/usr/bin/env python3
import vitis
import os
import shutil

# This script is auto-generated by Vitis IDE

print("\n---------------------------------------------------------")
print("  Migrating classic Vitis projects to Vitis Unified IDE  ")
print("---------------------------------------------------------")

# Create Vitis client
client = vitis.create_client()
client.update_workspace('C:/Users/Chris/Desktop/RiscV-NPU-DualCore/RISCVCORE/hello_world_convert')
print('Successfully created Vitis client on workspace {}'.format(client.get_workspace()))

print("Migrating projects from classic Vitis IDE")

vitis.dispose()
