domain_path: C:\Users\Chris\Desktop\RiscV-NPU-DualCore\RISCV32I_ZYNQCORE\2024.2VITIS\RiscV_Core\export\RiscV_Core\sw\standalone_ps7_cortexa9_0
app_src_dir: F:\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
